### PR TITLE
Create yarn build workflow

### PR DESCRIPTION
**Pull request by mprat**
Create Github Actions workflow to always install and build with yarn to ensure no issues in production.

Note: the current version of `main` is not buildable - this CI will pass once #27 is merged.

One additional change (pinning `autoprefixer`) had to be done to remove one additional CI warning per https://github.com/twbs/bootstrap/issues/36259. Had to upgrade to the 5.2.0-beta release of bootstrap to get this to pass CI. Issue created to track moving away from beta: https://github.com/mitoc/mitoc-gear-ui/issues/30

### CODE REVIEW

**Review by fpagnoux — APPROVED** [review]
Thanks for adding that! It should help us catch merge issues faster!

**Comment by mprat** [comment]
Thanks; I'll wait to merge this until the build is actually working (the linked PR) methinks.

**Comment by fpagnoux** [comment]
I'll open a side-PR to handle these warnings

**Comment by fpagnoux** [comment]
https://github.com/mitoc/mitoc-gear-ui/pull/29

**Comment by mprat** [comment]
Oh ok cool. If you're ok with this being broken, then do you want to
merge-override this one?

**Comment by mprat** [comment]
Oh, nope, got it; merge that one first then this one. Approved #29.

**Comment by fpagnoux** [comment]
Just merged 29, so if you merge `main` in this branch, hopefully tests will pass 🤞

**Comment by mprat** [comment]
@fpagnoux See my comment about bootstrap (in #30); we have to run the beta of that to fix a downstream dependency issue with a different node package.

Regardless, CI now passes!

**Pull request merged**
