### PR TITLE
Prune dependencies for prod deployment

### PR DESCRIPTION
**Pull request by mprat**
When working on deploying this repo to prod (https://github.com/mitoc/geardb-ansible/issues/21), two changes were made as a result:

There turned out to be ~600MB of dependencies that needed to be installed. Looking closer, some of these were test dependencies; this PR moves those into `devDependencies` instead.

Details:

After running `yarn install --frozen-lockfile --production` with the original repo:
```
603M	node_modules/
```

Largest packages

```
900K	node_modules/clean-css
904K	node_modules/jest-environment-jsdom
904K	node_modules/jest-environment-node
908K	node_modules/babel-preset-react-app
908K	node_modules/jest-serializer
908K	node_modules/regenerator-transform
936K	node_modules/jest-mock
940K	node_modules/@react-aria
984K	node_modules/jest-watcher
996K	node_modules/esquery
```

After moving the testing dependencies, running `yarn install --production`:

```
433M	node_modules/
```

largest packages:
```
748K	node_modules/common-tags
756K	node_modules/neo-async
760K	node_modules/tsutils
816K	node_modules/core-js-compat
824K	node_modules/react-router-dom
828K	node_modules/resolve-url-loader
836K	node_modules/source-map
852K	node_modules/@pmmmwh
856K	node_modules/react-router
904K	node_modules/@csstools
912K	node_modules/clean-css
996K	node_modules/esquery
```

This saves ~150MB of space on the resource-limited production machine, but still enables development.

(why `jest` and various `jest`-related dependencies are installed for production, who knows. probably some downstream dependency packages were not careful about what is in their `dependencies` vs. `devDependencies`)

### CODE REVIEW

**Comment by mprat** [comment]
Will get back to this once #27 and #28 are merged; for now, this will stay a draft.

**Comment by fpagnoux** [comment]
image

**Comment by mprat** [comment]
(should merge #28, then make sure CI passes for this before merging)

**Comment by fpagnoux** [comment]
@mprat should we just merge this PR? Seems like the CI is passing

**Review by fpagnoux — APPROVED** [review]

**Pull request merged**
