### PR TITLE
Handle office hours signups and credit requests in the gear database

### PR DESCRIPTION
**Pull request by fpagnoux**
Depends on https://github.com/mitoc/gear-db-django/pull/380

This PR (alongside its equivalent on the backend side) integrates office hour signups, credit request and credit approval to the gear database itself.

## Motivations 

  - Track better who runs office hours, in order to:
    - recognize the work of super-volunteers
    - Know who's our active volunteer population
  - Stop granting edit access to the MITOC calendar to all desk workers without ever revoking it. 
    - This has cause many issues in the past, from personal medical appointments being accidentally added there, to accidental removal of all scheduled office hour. 
  - Streamline the credit request and approval process so that we don't need to go to an external (Google Forms) provider, so that everything desk-related lives in the same place. 

## Suggested Workflow

- Volunteers sign up for office hours directly from the app:
image
- When they do, the app hits the google calendar API to edit the event title to add the volunteer's first name. 
- Volunteers can also simply cancel their signup
image
- Once they are done running the office hour, desk workers can fill a form in the app to request desk credit. They can pick which office hour they're requesting credit for based on their signups:
image
- The desk captain(s) is/are notified over email about the credit request. They can then approve them, and set the amount of desk credit they want to grant. 
image
- Volunteers can ask credit for other events than a classic office hour (e.g. inventory, work day). In this case, they can request credit without having previously signed up for office hour. This also handles the case where a volunteer forgot to sign up for office hours and asks credits after the OH's day. 
image

### CODE REVIEW

**Comment by luthern** [comment]
How will the VP (or other bod delegate) force add credit for students with financial need in this model? Will the manual addition be removed? If so, will there be another page for that process?

**Comment by luthern** [comment]
Since I didn’t say it in the previous comment — thanks a lot for this! It looks like a big improvement.

**Comment by fpagnoux** [comment]
> How will the VP (or other bod delegate) force add credit for students with financial need in this model? Will the manual addition be removed? If so, will there be another page for that process?

No, that part won't change. I'm not removing the manual process, any bod member can still add desk credit people. It's just that for the particular case of office hour, you won't have to do it manually.

**Comment by janfari** [comment]
This looks great!! Question about the automatic calendar syncing, will it still be possible for captains to manually add notes to particular office hours (like "Returns only") without breaking anything?

**Comment by fpagnoux** [comment]
Yes, but you'll have to be little careful when editing the title, so that it follows a specific structure.
For instance, you can name an office hour `Office Hours - - Returns only` but not `Office Hours - Returns only` (note the 2 dashes). Otherwise our automation will think `Returns only` is the name of a desk worker...
Once we get this PR in I can send you more details.

**Pull request merged**
